
GEMINI_API_KEY = '/CodeGuardian/GEMINI_API_KEY'
GITHUB_WEB_SECRET = '/CodeGuardian/GITHUB_WEB_SECRET'
GITHUB_API_KEY = '/CodeGuardian/GITHUB_API_KEY'
GITLAB_WEB_SECRET = '/CodeGuardian/GITLAB_WEB_SECRET'
GITLAB_API_KEY = '/CodeGuardian/GITLAB_API_KEY'
S3_BUCKET_NAME = '/CodeGuardian/S3_BUCKET_NAME'
SQS_URL = '/CodeGuardian/SQS_URL'